/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.News

import com.github.kittinunf.fuel.httpGet
import org.isen.News.controller.NewsController
import org.isen.News.model.data.Articles
import org.isen.News.model.impl.ArticleModel
import org.isen.News.view.INewsView
import org.isen.News.view.impl.NewsView


fun main() {
//  var m:ArticleModel = ArticleModel()
//  var c:NewsController = NewsController(m)
//  var v:INewsView = NewsView(c)
//
//  m.nb = 10
//    var url= "https://newsapi.org/v2/everything?q=tesla&from=2023-11-23&sortBy=publishedAt&apiKey=d46c0fcca35843d481d37e7b3668f168"
//    val (request, response, result) = url.httpGet().responseObject(
//        Articles.Deserializer())
//    val (si, error) = result
//    if (si != null) {
//        println("select an article:")
//        val input = readLine()
//        val entier = input?.toInt()
//        println("Vous avez saisi : $entier")
//        println("Author : ${si.articles[entier!!].author}")
//    } else {
//        println("error because News list must not be null : $error")
//    }

}
