/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.News

import com.github.kittinunf.fuel.httpGet
import org.isen.News.controller.NewsController
import org.isen.News.model.data.Article
import org.isen.News.model.impl.NewsModel
import org.isen.News.view.impl.NewsDetailsView
import org.isen.News.view.impl.NewsView


fun main() {
//  var m:NewsModel = NewsModel()
//  var c:NewsController = NewsController(m)
//  var v:INewsView = NewsView(c)
//
//  m.nb = 10
//    var url= "https://newsapi.org/v2/everything?q=tesla&from=2023-11-23&sortBy=publishedAt&apiKey=d46c0fcca35843d481d37e7b3668f168"
//    val (request, response, result) = url.httpGet().responseObject(
//        Articles.Deserializer())
//    val (si, error) = result
//    if (si != null) {
//        println("select an article:")
//        val input = readLine()
//        val entier = input?.toInt()
//        println("Vous avez saisi : $entier")
//        println("Author : ${si.articles[entier!!].author}")
//    } else {
//        println("error because News list must not be null : $error")
//    }

//    val everythingURL:String = "https://newsapi.org/v2/everything"
//    val search_topic:String= "q=tesla"
//    val apiKey:String = "apiKey=d46c0fcca35843d481d37e7b3668f168"
//
//    var article:Article? = null
//    var URL_topic = everythingURL + "?" + search_topic + "&" + apiKey
//
//    println("gfyughyuihgvhjuih")
//    val (request, response, result) = URL_topic.httpGet().responseObject(
//        Article.Deserializer())
//    val (si, error) = result
//    if (si != null) {
//        article = si
//        println("Author : ${si.articles[0]}")
//    } else {
//        println("error because News list must not be null : $error")
//    }

    var model:NewsModel = NewsModel()
    var controller:NewsController = NewsController(model)
    var vue1: NewsView = NewsView(controller)
    var vue2: NewsDetailsView = NewsDetailsView(controller)

    controller.displayViews()
    controller.loadStationInformation()



}


